const mongoose = require("mongoose");

const courseSchema = new mongoose.Schema(
  {
    cid: { type: String, required: true, unique: true }, // Unique course identifier (like Drizzle cid)
    name: { type: String, required: true },
    description: { type: String, default: "" },
    noOfChapters: { type: Number, required: true },
    includeVideo: { type: Boolean, default: false },
    level: { type: String, required: true },
    category: { type: String, default: "" },

    // JSON generated by AI (entire course structure)
    courseJson: { type: Object, default: {} },

    bannerImageUrl: { type: String, default: "" },

    // AI-generated + YouTube enriched course content
    courseContent: [
      {
        youtubeVideo: [
          {
            videoId: String,
            title: String,
          },
        ],
        courseData: {
          chapterName: String,
          topics: [
            {
              topic: String,
              content: String,
            },
          ],
        },
      },
    ],

    // Reference to course creator (user)
    user: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
  },
  { timestamps: true }
);

module.exports = mongoose.model("Course", courseSchema);
